In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

import os
print(os.listdir("../input"))

# Any results you write to the current directory are saved as output.

['train.csv', 'sample_submission.csv', 'test.csv']


In [2]:
import numpy as np
import pandas as pd

In [3]:
data_train = pd.read_csv("../input/train.csv")
data_test = pd.read_csv("../input/test.csv")
data_submission = pd.read_csv("../input/sample_submission.csv")

In [4]:
data_submission.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [5]:
data_train.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [6]:
data_test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [7]:
#Visualize some images
X = data_train.iloc[:,1:]
y = data_train.iloc[:,0]
X = np.asarray(X)
y = np.asarray(y)
# Normalize the data
#X = X/ 255.0

In [8]:
X = X.reshape(-1,28,28,1)

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=42)

In [11]:
X_train.shape

(29400, 28, 28, 1)

In [12]:
X_test.shape

(12600, 28, 28, 1)

In [13]:
from keras.utils.np_utils import to_categorical

Using TensorFlow backend.
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarn

In [14]:
X_train = X_train.reshape((29400, 28, 28, 1))
X_train = X_train.astype('float32') / 255
X_test = X_test.reshape((12600, 28, 28, 1))
X_test = X_test.astype('float32') / 255
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [15]:
y_train.shape

(29400, 10)

In [16]:
import matplotlib.pyplot as plt
%matplotlib inline

In [17]:
from keras.layers import Dense, Conv2D, MaxPooling2D, Dropout, Flatten, BatchNormalization
from keras import Sequential

### Listing 5.` Instantiating a small conv-net.

In [18]:
from keras import layers
from keras import models

In [19]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3,3), activation='relu', input_shape= (28,28,1)))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))
model.add(layers.Conv2D(64, (3,3), activation='relu'))
#model.add(layers.Conv2D(128, (3,3), activation='relu'))
#model.add(layers.MaxPooling2D((2,2)))
#model.add(layers.Conv2D(256, (3,3), activation='relu'))
#model.add(layers.MaxPooling2D((2,2)))
#Flaten the 3D conv-net to 1D for the Dense layers
model.add(layers.Flatten())
#model.add(layers.Dense(256, activation='relu'))
#model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

In [20]:
model.compile(optimizer='adam',
             loss='categorical_crossentropy',
             metrics=['accuracy'])

In [21]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 3, 3, 64)          36928     
_________________________________________________________________
flatten_1 (Flatten)          (None, 576)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 64)                36928     
__________

### Example of using .flow(x, y):

In [22]:
from keras.preprocessing.image import ImageDataGenerator

In [23]:
#datagen = ImageDataGenerator(
#    #featurewise_center=True,
#    #featurewise_std_normalization=True,
#    rotation_range=10, #10,15,25
#    zoom_range = 0.10,
#    width_shift_range=0.1,
#    height_shift_range=0.1)
#  rotation_range=10,  
#  zoom_range = 0.10,  
#  width_shift_range=0.1, 
#  height_shift_range=0.1
#validation_data = (X_val2,Y_val2), callbacks=[annealer]

In [24]:
# compute quantities required for featurewise normalization
# (std, mean, and principal components if ZCA whitening is applied)
#datagen.fit(X_train)

In [25]:
from keras.callbacks import LearningRateScheduler
annealer = LearningRateScheduler(lambda x: 1e-3 * 0.95 ** x)

In [26]:
#model.fit(X_train, y_train, epochs=5, batch_size=64)
#model.fit(X_train, y_train, batch_size=8, epochs=10, validation_data=(X_test, y_test))
model.fit(X_train, y_train, batch_size=8, epochs=100, validation_data=(X_test, y_test))
#model.fit(X_train, y_train, batch_size=128, epochs=100, validation_data=(X_test, y_test),
#         callbacks=[annealer])

Train on 29400 samples, validate on 12600 samples
Epoch 1/100
29400/29400 [==============================] - 29s 989us/step - loss: 0.1673 - acc: 0.9468 - val_loss: 0.0740 - val_acc: 0.9779
Epoch 2/100
29400/29400 [==============================] - 25s 867us/step - loss: 0.0595 - acc: 0.9820 - val_loss: 0.0479 - val_acc: 0.9852
Epoch 3/100
29400/29400 [==============================] - 26s 901us/step - loss: 0.0400 - acc: 0.9873 - val_loss: 0.0462 - val_acc: 0.9848
Epoch 4/100
29400/29400 [==============================] - 26s 869us/step - loss: 0.0315 - acc: 0.9897 - val_loss: 0.0473 - val_acc: 0.9865
Epoch 5/100
29400/29400 [==============================] - 25s 863us/step - loss: 0.0246 - acc: 0.9925 - val_loss: 0.0516 - val_acc: 0.9857
Epoch 6/100
29400/29400 [==============================] - 25s 864us/step - loss: 0.0212 - acc: 0.9939 - val_loss: 0.0489 - val_acc: 0.9866
Epoch 7/100
29400/29400 [==============================] - 26s 881us/step - loss: 0.0186 - acc: 0.9941 - val_l

In [27]:
#epochs= 50 #100
# DECREASE LEARNING RATE EACH EPOCH
#annealer = LearningRateScheduler(lambda x: 1e-3 * 0.95 ** x)
# fits the model on batches with real-time data augmentation:

#model.fit_generator(datagen.flow(X_train, y_train, batch_size=32),
#                    steps_per_epoch=len(X_train) / 32, epochs=epochs, 
#                    validation_data = (X_test,y_test),
#                   callbacks=[annealer])

In [28]:
#y_train = np_utils.to_categorical(y_train, num_classes=6)

In [29]:
predicted_val = model.predict(X_test)

In [30]:
print(np.argmax(predicted_val[:,:]))

8


In [31]:
print(predicted_val)

[[0. 0. 0. ... 0. 1. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [32]:
# select the indix with the maximum probability
results = np.argmax(predicted_val,axis = 1)

results = pd.Series(results,name="Label")

In [33]:
len(results)

12600

In [34]:
df_test = pd.read_csv("../input/test.csv")

In [35]:
df_test.head()

pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  pixel8  \
0       0       0       0       0       0       0       0       0       0   
1       0       0       0       0       0       0       0       0       0   
2       0       0       0       0       0       0       0       0       0   
3       0       0       0       0       0       0       0       0       0   
4       0       0       0       0       0       0       0       0       0   

   pixel9  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 784 columns]

In [36]:
data_submission.head()

ImageId  Label
0        1      0
1        2      0
2        3      0
3        4      0
4        5      0

In [37]:
data_submission.shape

(28000, 2)

In [38]:
X_test = df_test
X_test = np.asarray(X_test)

In [39]:
X_test = X_test.reshape(-1,28,28,1)

In [40]:
X_test.shape

(28000, 28, 28, 1)

In [41]:
predicted_val = model.predict(X_test)

In [42]:
# select the indix with the maximum probability
results = np.argmax(predicted_val,axis = 1)

results = pd.Series(results,name="Label")

In [43]:
results
data_submission.tail()

ImageId  Label
27995    27996      0
27996    27997      0
27997    27998      0
27998    27999      0
27999    28000      0

In [44]:
data_submission['Label']=results

In [45]:
data_submission.head()

ImageId  Label
0        1      2
1        2      0
2        3      9
3        4      0
4        5      3

In [46]:
data_submission.tail()

ImageId  Label
27995    27996      9
27996    27997      7
27997    27998      3
27998    27999      9
27999    28000      2

In [47]:
#submission = pd.concat([pd.Series(range(1,28001),name = "ImageId"),results],axis = 1)

data_submission.to_csv("cnn_mnist_submission_6.csv",index=False)